import { useState, useMemo, useCallback } from 'react';
import type { LatLngBounds } from 'leaflet';
import { Satellite, Copy, Check, ChevronDown, ChevronUp } from 'lucide-react';

// ── Canopy growth projection curve ──
// Ported from legacy-with-copilot.html's NDVI_PROJECTION. This is an
// illustrative aggregate projection (typical NDVI trajectory for a new
// plantation over its first 5 years), NOT a per-plant measurement — real
// per-plant data lives in growthDb's growth_readings table instead.
const NDVI_PROJECTION = [
  { year: 2026, factor: 0.29, label: '২০২৬ (চারা)', canopy: 'তরুণ চারা চাদর (Young)' },
  { year: 2027, factor: 0.38, label: '২০২৭', canopy: 'বর্ধনশীল চারা (Growing)' },
  { year: 2028, factor: 0.5, label: '২০২৮', canopy: 'মাঝারি চাদর (Medium)' },
  { year: 2029, factor: 0.62, label: '২০২৯', canopy: 'ঘন চাদর (Dense)' },
  { year: 2030, factor: 0.73, label: '২০৩০', canopy: 'পরিপক্ক চাদর (Mature)' },
  { year: 2031, factor: 0.82, label: '২০৩১ (পরিপক্ক)', canopy: 'নিবিড় বনাঞ্চল (Old Growth)' },
];

function offsetLevelFor(factor: number): { label: string; pct: number; color: string } {
  if (factor < 0.35) return { label: 'নিম্ন', pct: 10, color: '#f59e0b' };
  if (factor < 0.5) return { label: 'মাঝারি', pct: 30, color: '#f59e0b' };
  if (factor < 0.7) return { label: 'উচ্চ', pct: 60, color: '#16a34a' };
  return { label: 'অত্যন্ত উচ্চ', pct: 90, color: '#15803d' };
}

const GEE_DATASETS = [
  { value: 'COPERNICUS/S2_SR_HARMONIZED', label: 'COPERNICUS/S2_SR_HARMONIZED (Sentinel-2 10m)' },
  { value: 'MODIS/006/MOD13Q1', label: 'MODIS/006/MOD13Q1 (250m NDVI 16-day)' },
  { value: 'LANDSAT/LC09/C02/T1_L2', label: 'LANDSAT/LC09/C02/T1_L2 (30m)' },
];
const GEE_BANDS = [
  { value: 'ndvi', label: 'NDVI (B8-B4)/(B8+B4)' },
  { value: 'evi', label: 'EVI Enhanced Vegetation Index' },
  { value: 'rgb', label: 'True Color Composite (B4,B3,B2)' },
];

function buildGeeScript(dataset: string, bands: string, cloudPct: number, bounds: LatLngBounds | null): string {
  let coords = '[[89.50, 25.40], [89.90, 25.40], [89.90, 26.20], [89.50, 26.20]]';
  if (bounds) {
    const sw = bounds.getSouthWest();
    const ne = bounds.getNorthEast();
    coords = `[[\n    [${sw.lng.toFixed(4)}, ${sw.lat.toFixed(4)}],\n    [${ne.lng.toFixed(4)}, ${sw.lat.toFixed(4)}],\n    [${ne.lng.toFixed(4)}, ${ne.lat.toFixed(4)}],\n    [${sw.lng.toFixed(4)}, ${ne.lat.toFixed(4)}]\n  ]]`;
  }
  let vis: string;
  if (bands === 'ndvi') {
    vis =
      "var vis = {min: 0, max: 1, palette: ['red','yellow','green']};\nvar ndvi = s2.map(function(img){\n  return img.normalizedDifference(['B8','B4']).rename('NDVI');\n}).median().clip(region);\nMap.addLayer(ndvi, vis, 'NDVI');";
  } else if (bands === 'evi') {
    vis =
      "var vis = {min: 0, max: 1, palette: ['red','yellow','green']};\nvar evi = s2.map(function(img){\n  var nir = img.select('B8'), red = img.select('B4'), blue = img.select('B2');\n  return nir.subtract(red).multiply(2.5)\n    .divide(nir.add(red.multiply(6)).subtract(blue.multiply(7.5)).add(1))\n    .rename('EVI');\n}).median().clip(region);\nMap.addLayer(evi, vis, 'EVI');";
  } else {
    vis = "var vis = {bands: ['B4','B3','B2'], min: 0, max: 3000};\nMap.addLayer(s2.median().clip(region), vis, 'True Color');";
  }
  return `// Generated by Plantation Tracker — paste at code.earthengine.google.com
var region = ee.Geometry.Polygon(${coords});
Map.centerObject(region, 12);

var s2 = ee.ImageCollection('${dataset}')
  .filterBounds(region)
  .filterDate(ee.Date(Date.now()).advance(-3, 'month'), ee.Date(Date.now()))
  .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', ${cloudPct}));

${vis}

print('Image count:', s2.size());
`;
}

interface NdviControllerProps {
  totalTrees: number;
  bounds: LatLngBounds | null;
}

export default function NdviController({ totalTrees, bounds }: NdviControllerProps) {
  const [open, setOpen] = useState(false);
  const [yearIdx, setYearIdx] = useState(0);
  const [dataset, setDataset] = useState(GEE_DATASETS[0].value);
  const [bandMode, setBandMode] = useState(GEE_BANDS[0].value);
  const [cloudPct, setCloudPct] = useState(10);
  const [copied, setCopied] = useState(false);
  const [geeScript, setGeeScript] = useState<string | null>(null);

  const p = NDVI_PROJECTION[yearIdx];
  // Small deterministic-ish jitter so the number doesn't look like a static
  // placeholder, without needing a real satellite call for this projection view.
  const ndviDisplay = useMemo(() => (p.factor + (((totalTrees * 7) % 10) / 10 - 0.5) * 0.04).toFixed(2), [p.factor, totalTrees]);
  const carbon = useMemo(() => (totalTrees * 0.022 * (p.factor / 0.82)).toFixed(1), [totalTrees, p.factor]);
  const offset = offsetLevelFor(p.factor);

  const handleGenerate = useCallback(() => {
    setGeeScript(buildGeeScript(dataset, bandMode, cloudPct, bounds));
    setCopied(false);
  }, [dataset, bandMode, cloudPct, bounds]);

  const handleCopy = useCallback(() => {
    if (!geeScript) return;
    navigator.clipboard?.writeText(geeScript).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [geeScript]);

  return (
    <div className="absolute top-2 sm:top-3 right-14 sm:right-16 z-[1000] w-64 sm:w-72">
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between gap-2 bg-white/95 backdrop-blur rounded-full shadow-lg px-3 py-2 text-xs font-bold text-emerald-800 cursor-pointer"
      >
        <span className="flex items-center gap-1.5"><Satellite size={14} /> NDVI নিয়ন্ত্রক</span>
        {open ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
      </button>

      {open && (
        <div className="mt-1.5 bg-white/97 backdrop-blur rounded-xl shadow-xl p-3 space-y-3 max-h-[70vh] overflow-y-auto">
          {/* Canopy growth projection */}
          <div>
            <p className="text-[10px] font-bold text-gray-600 mb-1">বৃদ্ধির প্রক্ষেপণ (Simulated Projection)</p>
            <input
              type="range" min={0} max={5} value={yearIdx}
              onChange={(e) => setYearIdx(Number(e.target.value))}
              className="w-full accent-emerald-700"
            />
            <div className="flex justify-between text-[8px] text-gray-400 px-0.5">
              {NDVI_PROJECTION.map((yp) => <span key={yp.year}>{yp.year}</span>)}
            </div>
            <div className="grid grid-cols-2 gap-1.5 mt-2">
              <div className="bg-emerald-50 rounded-lg p-1.5 text-center border border-emerald-100">
                <div className="text-[8px] text-gray-500">গড় NDVI</div>
                <div className="text-sm font-bold text-emerald-700">{ndviDisplay}</div>
                <div className="text-[7px] text-emerald-600">{p.canopy}</div>
              </div>
              <div className="bg-blue-50 rounded-lg p-1.5 text-center border border-blue-100">
                <div className="text-[8px] text-gray-500">মোট চারা</div>
                <div className="text-sm font-bold text-blue-700">{totalTrees}</div>
              </div>
              <div className="bg-teal-50 rounded-lg p-1.5 text-center border border-teal-100">
                <div className="text-[8px] text-gray-500">কার্বন শোষণ</div>
                <div className="text-sm font-bold text-teal-700">{carbon}</div>
                <div className="text-[7px] text-teal-600">টন/বছর</div>
              </div>
              <div className="bg-amber-50 rounded-lg p-1.5 text-center border border-amber-100">
                <div className="text-[8px] text-gray-500">অফসেট মাত্রা</div>
                <div className="text-xs font-bold" style={{ color: offset.color }}>{offset.label}</div>
                <div className="w-full bg-gray-200 rounded-full h-1 mt-0.5">
                  <div className="h-1 rounded-full transition-all" style={{ width: offset.pct + '%', background: offset.color }} />
                </div>
              </div>
            </div>
          </div>

          <div className="border-t pt-2">
            <p className="text-[10px] font-bold text-gray-600 mb-1">☁️ Earth Engine স্ক্রিপ্ট জেনারেটর</p>
            <select value={dataset} onChange={(e) => setDataset(e.target.value)} className="w-full text-[10px] border rounded px-1.5 py-1 mb-1">
              {GEE_DATASETS.map((d) => <option key={d.value} value={d.value}>{d.label}</option>)}
            </select>
            <select value={bandMode} onChange={(e) => setBandMode(e.target.value)} className="w-full text-[10px] border rounded px-1.5 py-1 mb-1">
              {GEE_BANDS.map((b) => <option key={b.value} value={b.value}>{b.label}</option>)}
            </select>
            <div className="flex items-center gap-1.5 mb-1.5">
              <input type="range" min={0} max={50} value={cloudPct} onChange={(e) => setCloudPct(Number(e.target.value))} className="flex-1 accent-emerald-700" />
              <span className="text-[9px] font-semibold text-gray-600 w-10">&lt;{cloudPct}%</span>
            </div>
            <button
              onClick={handleGenerate}
              className="w-full bg-emerald-700 hover:bg-emerald-800 text-white text-[10px] font-semibold py-1.5 rounded-lg cursor-pointer"
            >
              স্ক্রিপ্ট তৈরি করুন (বর্তমান ম্যাপ এলাকার জন্য)
            </button>
            {geeScript && (
              <div className="mt-1.5 relative">
                <pre className="bg-gray-900 text-emerald-300 text-[8px] p-2 rounded-lg overflow-x-auto max-h-32 whitespace-pre-wrap">{geeScript}</pre>
                <button
                  onClick={handleCopy}
                  className="absolute top-1 right-1 bg-white/90 rounded px-1.5 py-0.5 text-[8px] font-semibold flex items-center gap-0.5 cursor-pointer"
                >
                  {copied ? <><Check size={10} /> কপি হয়েছে</> : <><Copy size={10} /> কপি</>}
                </button>
              </div>
            )}
            <p className="text-[8px] text-gray-400 mt-1">code.earthengine.google.com এ পেস্ট করে চালান — কোনো API কী প্রয়োজন নেই।</p>
          </div>
        </div>
      )}
    </div>
  );
}
